# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins: ["jekyll-paginate"]
paginate: 5

# Site settings
title: George's Blog
email: george@usermod.net
description: > # this means to ignore newlines until "baseurl:"
    I'm George Angelopoulos and I like computers, cycling, cats, and other things.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "https://usermod.net"
#twitter_username: g_usermod
github_username:  gangelop
linkedin_username:  gangelop

# Build settings
markdown: kramdown
include: [".well-known"]
